"use client";
import ArticleSection from "./ArticleSection";
import CommunitySection from "./CommunitySection";
import WeatherEffects from "./WeatherEffects";
import { apiBaseUrl } from "./apiBase";
import { FormEvent, useState } from "react";
type WeatherData = { location: { name: string; admin1?: string; country: string }; current: { temperature_2m: number; apparent_temperature: number; relative_humidity_2m: number; wind_speed_10m: number; weather_code: number }; daily: { time: string[]; weather_code: number[]; temperature_2m_max: number[]; temperature_2m_min: number[] } };
const labels: Record<number,string> = {0:"Céu limpo",1:"Predominantemente limpo",2:"Parcialmente nublado",3:"Nublado",45:"Neblina",48:"Neblina com geada",51:"Garoa leve",53:"Garoa moderada",55:"Garoa intensa",61:"Chuva leve",63:"Chuva moderada",65:"Chuva forte",71:"Neve leve",73:"Neve moderada",75:"Neve forte",80:"Pancadas de chuva",81:"Pancadas moderadas",82:"Pancadas fortes",95:"Trovoadas",96:"Trovoadas com granizo",99:"Trovoadas fortes"};
function label(code:number){return labels[code] ?? "Condição variável";}
export default function Home(){
 const [city,setCity]=useState("São Paulo"); const [data,setData]=useState<WeatherData|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 async function search(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");try{const base=process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001";const response=await fetch(base+"/api/weather?city="+encodeURIComponent(city));const result=await response.json();if(!response.ok)throw new Error(result.error ?? "Não foi possível consultar o tempo.");setData(result);}catch(problem){setError(problem instanceof Error?problem.message:"Erro inesperado.");setData(null);}finally{setLoading(false);}}
 return <main className="shell"><header className="topbar"><a className="brand" href="#">☀ <span>clima<span className="brand-light">agora</span></span></a><span className="top-note">Tempo claro, decisões melhores</span></header><section className="hero"><div className="eyebrow"><span className="live-dot"/> MONITORAMENTO DO TEMPO</div><h1>O tempo da sua cidade,<br/><em>sempre por perto.</em></h1><p className="intro">Previsão simples para você planejar o seu dia.</p><form className="search" onSubmit={search}><span aria-hidden="true">⌕</span><input aria-label="Nome da cidade" value={city} onChange={e=>setCity(e.target.value)} placeholder="Busque uma cidade"/><button disabled={loading||!city.trim()}>{loading?"Buscando…":"Ver previsão"}</button></form>{error&&<p className="error" role="alert">{error}</p>}</section>
 {data?<section className="weather" aria-live="polite"><WeatherEffects className="weatherEffects" weatherCode={data.current.weather_code} temperature={data.current.temperature_2m} /><div className="weather-heading"><div><span className="section-label">AGORA EM</span><h2>{data.location.name}<span>{[data.location.admin1,data.location.country].filter(Boolean).join(", ")}</span></h2></div><span className="weather-icon">{data.current.weather_code>=51?"🌧":data.current.weather_code>=2?"⛅":"☀️"}</span></div><div className="current"><strong>{Math.round(data.current.temperature_2m)}°</strong><div><b>{label(data.current.weather_code)}</b><span>Sensação de {Math.round(data.current.apparent_temperature)}°</span></div></div><div className="details"><div><span>UMIDADE</span><b>{data.current.relative_humidity_2m}%</b></div><div><span>VENTO</span><b>{Math.round(data.current.wind_speed_10m)} km/h</b></div></div><div className="forecast-title"><h3>Próximos dias</h3><span>PREVISÃO LOCAL</span></div><div className="days">{data.daily.time.map((day,index)=><article className="day" key={day}><span>{index===0?"Hoje":new Intl.DateTimeFormat("pt-BR",{weekday:"short",timeZone:"UTC"}).format(new Date(day+"T12:00:00Z"))}</span><span className="day-icon">{data.daily.weather_code[index]>=51?"🌧":data.daily.weather_code[index]>=2?"⛅":"☀️"}</span><small>{label(data.daily.weather_code[index])}</small><b>{Math.round(data.daily.temperature_2m_max[index])}° <i>{Math.round(data.daily.temperature_2m_min[index])}°</i></b></article>)}</div></section>:<section className="empty"><span className="empty-icon">☼</span><p>Busque sua cidade para ver<br/>a previsão dos próximos dias.</p></section>}
 <ArticleSection />
 <footer><span>Projeto Clima</span><span>Dados meteorológicos via Open-Meteo</span></footer></main>;
}
